### numpy 배열 생성하기

1. import 해야 사용가능하고
2. array() 사용
3. random의 함수들 사용

In [1]:
import numpy as np

In [6]:
#1. array()를 사용해서 np배열을 생성
'''
1. list는 출력결과가 [] 안에 ,로 구분
2. npArray는 출력결과가 [] 안에 ,로 구분되지 않음. (정식적으로 print안에 넣어서 출력시)
3. np배열은 nparr객체 타입으로 나온다.
   ndarray객체 다차원 행렬구조를 지원하는 numpy의 핵심 구조이다.
'''

myList = [4,5,6,7]
print(myList)

myArr = np.array(myList)
print(myArr)

print(type(myList))
print(type(myArr))

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>


In [18]:
subL = myList[1:3]
print(subL)

subA = myArr[1:3]
print(subA)

subL[0] =-5
subA[0] = -5

print(subL)
print(subA)

print(myList)
print(myArr) #numpy 배열은 리스트와 동일하지만, 슬라이싱한 객체를 변경하면 원본객체도 변경됨

[5, 6]
[-5  6]
[-5, 6]
[-5  6]
[4, 5, 6, 7]
[ 4 -5  6  7]


In [102]:
#2. 랜덤함수 사용해서 생성.
# rand(개수), randint()

a= np.random.rand(5)
print(a)
print(type(a)) 

b= np. random.randint(1,10,5) #1~9
print(b)

c = np.random.randn(10)#가우시안 정규분포
print(c)

[0.64278724 0.75568852 0.43866655 0.0831498  0.65137002]
<class 'numpy.ndarray'>
[4 6 2 8 4]
[ 1.63493131  1.36808741 -1.56929857 -0.91085874 -1.73342579 -0.64964521
  0.37896396  0.84512045  0.05617546  0.90340244]


In [29]:
#list와의 차이점
'''
list는 서로 다른 자료형이 묶일 수 있음
array는 서로 다른 자료형이 묶일 수 없음
    - 서로 다른 자료형을 넣으면 범위가 큰 데이터 타입으로 묶인다 (정수vs문자->문자 정수vs실수->실수)
아래와 같은 제약을 가지는 이유는 내부 원소에 대한 접근과 반복문 실행을 빨리하기 위함임
'''
li = [1,2,3,'4',5,6,7] 
arr = np.array(li) 
arr2 = np.array([1,2,3,4.0,33,2,5])
arr3 = np.array([1.0,2.0,3.0,4.0,5.0], dtype="int32") #dtype :int32 , float32.. 
print(li)
print(arr)
print(arr2)
print(arr3)

[1, 2, 3, '4', 5, 6, 7]
['1' '2' '3' '4' '5' '6' '7']
[ 1.  2.  3.  4. 33.  2.  5.]
[1 2 3 4 5]


### 배열 초기화

In [25]:
# 1. 0 값으로 초기화 zeros()로 사용
az = np.zeros(10) # 0.0으로 초기화 됨
print(az)

#2. 1값으로 초기화 ones()
ao = np.ones(10)
print(ao)

#3. 3값으로 초기화? 
am = np.zeros(10)+3
print(am)

#4.
ae = np.eye(3) #3자리에 n을 넣으면 n*n 초기화의 의미보다 그냥 행렬을 만들어 놓는것
print(ae)

#5. arrage()
print(np.arange(3))
print(np.arange(0,3))
print(np.arange(3,10,2))

#6. full()
af = np.full((5,5),-11.0, dtype='int32') #shape:행과열 (1차원 배열은 숫자만, 2차원배열은 (n,n)의 형태) dtype은 값의 형태
print(af)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2]
[0 1 2]
[3 5 7 9]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]


### Numpy 배열의 속성과 기본함수
1. ndim : 차원 확인
2. shape : 몇행 몇열인지?
3. reshape : 1차원을 2차원으로 바꿀 수 있음(차원을 바꿈, 전체 데이터 개수는 동일)
4. size : 요소의 개수
5. dtype : 속성
6. type(): 객체의 변수값을 알 수 있음

In [33]:
# arr1= np.array([[1.0,2,3],[4,5,6]],dtype="int32")
arr1= np.array([[1.0,2,3],[4,5,6]],dtype = np.int32)
print(arr1)

[[1 2 3]
 [4 5 6]]


In [46]:
print(type(arr1))
print(np.ndim(arr1))
print(np.shape(arr1))
print(np.size(arr1))
print()
print('*'*30)
print()
#arr1 배열의 요소값 타입을 한번에 바꿀때 사용
arr1_1 = arr1.astype(np.float64) # astype() == dtype 요소에 해당하는것들을 변경해줌
print(arr1_1)
print(type(arr1_1))
print()
print('*'*30)
print()
arr2 = np.arange(32)
arr2_1 = arr2.reshape(8,4)
print(arr2)
print(arr2_1)

<class 'numpy.ndarray'>
2
(2, 3)
6

******************************

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>

******************************

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### 랜덤함수와 seed값 설정하기 

Numpy의 Random 모듈(SubPackage)에는 난수를 생성하는 다양한 함수들이 존재
그 중에서 가장 많이 사용되는 3가지를 정리

- rand(행,열): 0~1사이의 실수값을 반환
- randn(행,열) : 가우시안 정규분포값
- randint(row,high,size) :

seed : random이지만 특정한 시작 숫자를 정하고 싶으면 seed사용

In [48]:
arr3 = np.random.randn(4,4)
arr3

array([[-0.33301831, -0.39556019, -0.17045541, -1.72289011],
       [-0.84563038, -0.42696902, -0.05909355,  0.6742449 ],
       [-0.29702644, -0.69544038,  1.17745178,  1.5172785 ],
       [-0.88485359,  1.34253173, -1.62058557,  0.47549103]])

In [50]:
# seed값 설정하기
#특정한 시작 숫자를 제공해서 난수를 발생-> 고정적인 난수가 발생
#실행할때마다 난수값이 바뀌지 않기 때문에 분석결과를 확인하는데 용이하다
#seed값은 한번만 정해주면 계속 유지되고 음수값은 안됨

np.random.seed(404) # 시드값이 같으면 랜덤값도 같음
arr3 = np.random.randn(4,4)
arr3

array([[-1.18269089,  1.33746165, -0.31430504,  0.5566431 ],
       [-0.20929933, -0.01180037,  1.23493345, -0.04341894],
       [-0.68178724,  1.20069197,  1.34394438, -0.834109  ],
       [ 1.0359977 ,  1.6657991 ,  0.94947856,  1.06700952]])