### 인덱싱, 슬라이싱

In [1]:
import numpy as np

In [3]:
narr = np.arange(5)
narr

array([0, 1, 2, 3, 4])

In [9]:
print(narr[1],narr[-1])
print(narr[1:])
print(narr[:])
print(narr[2:4])

1 4
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [ ]:
'''
2차원 배열에서의 인덱싱, 슬라이싱
인덱스는 [,] 콤마를 기준으로 두개의 인자를 받는다
앞 인자값은 행의 idx, 뒤의 인자값은 열의 idx

,없이 넣으면 모든 행과 모든 열을 포함한다.
'''

In [35]:
np.random.seed(100) #seed는 한번만 줘도 전체페이지에서 적용됨
narr1 = np.random.randint(0,20,16).reshape(4,4)
print(narr1)

[[ 8  3  7 15]
 [16 10  2  2]
 [ 2 14  2 17]
 [16 15  4 11]]


In [46]:
#1. narr1에서 첫번째줄 7을 가져올것
print(narr1[0,2])

#2. 두번째라인 [16,10,2,2]
print(narr1[1,])
print(narr1[1,0:])
print(narr1[1,:])
print(narr1[1:2,:]) #2차원으로 출력됨

#3. 전체행에 대해서 4번째 열만 다 가져오려면? 
print(narr1[:,3])
print(narr1[0:4,3])
print(narr1[0:4,3:4])
print(narr1[0:4,3:])
# print(narr1[,3]) 안됨

#4. 전체행에 대해서 1,2번째 열만 가져올것.
print(narr1[:,1:3])

7
[16 10  2  2]
[16 10  2  2]
[16 10  2  2]
[[16 10  2  2]]
[15  2 17 11]
[15  2 17 11]
[[15]
 [ 2]
 [17]
 [11]]
[[15]
 [ 2]
 [17]
 [11]]
[[ 3  7]
 [10  2]
 [14  2]
 [15  4]]


### 인덱싱과 조건 슬라이싱

In [75]:
np.random.seed(0)
arr3 = np.random.randn(4,4)
print(arr3)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


In [54]:
#1. 논리연산자 사용
print(arr3[arr3>0])
print(arr3[arr3<0])

#2. 0보다 작은 값은 전부 0으로 치환
arr3[arr3<0] = 0
print(arr3) #원본도 바뀜 

[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799 0.95008842
 0.4105985  0.14404357 1.45427351 0.76103773 0.12167502 0.44386323
 0.33367433]
[-0.97727788 -0.15135721 -0.10321885]
[[1.76405235 0.40015721 0.97873798 2.2408932 ]
 [1.86755799 0.         0.95008842 0.        ]
 [0.         0.4105985  0.14404357 1.45427351]
 [0.76103773 0.12167502 0.44386323 0.33367433]]


### 3. WHERE 함수


In [65]:
'''
arr3가 0보다 크면 arr3를 그대로 리턴
arr3가 0 보다 작으면 -1로 리턴
'''

arr3_1 =np.where(arr3>0,arr3,-1) #각각의 항을 조건식과 비교한 다음 명시된 값으로 변경해줌
print(arr3_1)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -1.          0.95008842 -1.        ]
 [-1.          0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


In [71]:
a = np.array([[1,2],[3,4],[5,6]])
bool_a = (a>2)
print(a[bool_a]) #알아서 비교해서 TRUE인 값만 출력

[3 4 5 6]


###  통계함수
- sum(데이터,axis) : 합 axis=0 행끼리의 합(한 열을 다 더하는것) axis=1 열끼리의 합(한 행을 다 더하는 것)
- min() : 최소
- max() : 최대
- mean() : 평균
- argmin() :
- argmax() :
- comsum() : 누적합

In [76]:
arr4 = np.random.randint(0,20,16).reshape(4,4)
print(arr4)

[[18  3 17 19]
 [19 19 14  7]
 [ 0  1  9  0]
 [10  3 11 18]]


In [87]:
print(np.sum(arr4))
print(np.sum(arr4,axis=0))
print(np.sum(arr4,axis=1))
print(np.cumsum(arr4, axis=0)) # 첫째행+둘째행+,,,+n번째행

print(np.argmax(arr4,axis=0)) #제일 큰 값의 인덱스를 반황함

168
[47 26 51 44]
[57 59 10 42]
[[18  3 17 19]
 [37 22 31 26]
 [37 23 40 26]
 [47 26 51 44]]
[1 1 0 0]
