### Pytorch 에서의 Gradient Descent
    - 머신러닝 과정에서 선형회귀(Linear Regression)에 대해 간단히 살펴 보았음.
    - 이번에는 파이토치를 이용하여 선형회귀(Linear Regression)을 위한 연산 그래프를 만들고, 경사하강법을 이해하는 코드를
    다시 작성해볼 것임.
    - 파이터치에서는 데이터의 기본단위 텐서(Tensor)를 사용한다.
    Numpy에서 np.array([1,2,3])과 동일한 것으로 이러한 텐서를 연산의 기본단위로 사용한다.
    - 텐서 생성 방법: torch.tensor()

In [1]:
import torch
import torchvision #pytorch lib에서 vision은 img processing에 특화된 라이브러리
import torch.nn as nn #nn: neural Network 
import numpy as np
import torchvision.transforms as transforms #transforms는 Data aumentation을 위한것.

In [5]:
X = torch.Tensor(2,3)
X #0에 가까운 값이 랜덤으로 입력됨
X.shape #== X.size

X = torch.Tensor([[1,2,3],[4,5,6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
'''
tensor() 인자값으로 data.dtype,device,requires_grad등이 있따.
dtype == data값의 타입지정
device == 텐서를 어느 기기에 올릴 것인지 지정할 수 있음 (CPU? GPU? - ANN의 경우 layer가 하나이기때문에 연산양이 적어 CPU로 돌릴 수 있음)
requires_grad == 텐서에 기울기를 지정할지 여부 (False) 
    - 미분 사용 여부 (안하면 backpropargation 진행이 안되서 학습이 안됨)
    - 하지만 TestData는 학습할 필요가 없으니까 False로 넣으면 됨
    - True의 경우 편미분을 해야되기 때문에 메모리를 굉장히 많이 잡아먹고 있음 그래서 False면 비교적 메모리를 적게 가져감
'''

# x = torch.tensor(data=[2.0,3.0],requires_grad = True)
x = torch.tensor(data=[2.0,3.0]) #밑에 loss.backword()에서 error
x

y = x**2
y

#1.예측값 출력
pred = 2*y+3 ## 2(x^2)+3
pred

target = torch.tensor([3.0,4.0])

#2. loss값을 구한다
loss = torch.sum(torch.abs(pred-target)) # (11-3) +(21-4) ==25 loss굉장히 높음
loss #25나옴 
print('Loss: ',loss)

#3. 가장 가파른 기울기로 하강하는 weight를 찾음 == 가장 낮은 loss값을 구하는 weight를 찾음 -> 미분 편미분 / backpropagation

loss.backward()
'''
x.grad --> dy/dw = x
w.grad --> dy/dx = w
'''
print(x.grad,pred.grad)

Loss:  tensor(25.)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### Tensor Type - tensor(), as_tensor()
    - Numpy 배열을 torch.Tensor 변형

In [23]:
'''
pytorch의 텐서 자료형은 numpy의 array()와 동일한 것으로 이해
'''

#1.
li = np.array([[1,2],[3,4]])
print(li)
print(li.dtype)
print(type(li))


print('*'*40)

li_torch = torch.tensor(li)
print(li_torch)
print(type(li_torch))

print('*'*40)

li_as_torch = torch.as_tensor(li)
print(li_as_torch)
print(type(li_as_torch))

print('*'*40)
#반대로 텐서를 numpy배열로 변형
li_tensor_numpy = li_as_torch.numpy()
print(li_tensor_numpy)
print(type(li_tensor_numpy))

[[1 2]
 [3 4]]
int32
<class 'numpy.ndarray'>
****************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
****************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
****************************************
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
