In [2]:
import numpy as np
from keras import datasets
from keras import models, layers
from keras.utils import np_utils

In [4]:
#1.DataLoader
(X_train,y_train),(X_test,y_test) = datasets.mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [6]:
print(X_train[0])
print(y_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

In [7]:
X_train.shape

(60000, 28, 28)

In [8]:
#2. 
L,W,H = X_train.shape

X_train = X_train.reshape(-1,W*H) #1차원으로 펼침
X_test = X_test.reshape(-1,W*H)

In [9]:
print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)


In [10]:
#입력데이터 전처리
X_train = X_train/255
X_test = X_test/255
print(X_train[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [11]:
#3. Y  입력 데이터 전처리
'''
output에서는 총 10개의 카테고리가 있다.
각각의 노드에서 이미지에 해당하는 예측 값을 
0~1사이의 확률 분포로 만들 필요가 있음
One Hot Encoding방식으로 변환해줌
np_uTILS.TO_CATEGORICAL()()함수를 사용한다
'''

Y_train = np_utils.to_categorical(y_train)
Y_test = np_utils.to_categorical(y_test)

In [12]:
print(Y_train)
print(Y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
#4. Setting Hyper_parameters
input_size = 28*28
hidden_size = 100
num_classes = 10
epochs = 10
batch_size = 100

In [16]:
#5. Model Generator
model = models.Sequential()
model.add(layers.Dense(hidden_size, activation='relu' ,input_shape=(input_size,)))
model.add(layers.Dense(num_classes,activation='softmax'))

In [17]:
#6. Compile
model.compile('sgd','categorical_crossentropy',metrics=['accuracy']) #metrics는 평가지표

In [18]:
#7.Learning
model.fit(X_train,Y_train,epochs=epochs,batch_size=batch_size,validation_split=0.2) #validation:Training = 2:8

Epoch 1/10
480/480 [==============================] - 1s 3ms/step - loss: 1.2176 - accuracy: 0.7010 - val_loss: 0.6477 - val_accuracy: 0.8600
Epoch 2/10
480/480 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.8633 - val_loss: 0.4494 - val_accuracy: 0.8883
Epoch 3/10
480/480 [==============================] - 1s 2ms/step - loss: 0.4424 - accuracy: 0.8851 - val_loss: 0.3832 - val_accuracy: 0.9004
Epoch 4/10
480/480 [==============================] - 1s 2ms/step - loss: 0.3891 - accuracy: 0.8956 - val_loss: 0.3478 - val_accuracy: 0.9072
Epoch 5/10
480/480 [==============================] - 1s 2ms/step - loss: 0.3574 - accuracy: 0.9019 - val_loss: 0.3254 - val_accuracy: 0.9122
Epoch 6/10
480/480 [==============================] - 1s 2ms/step - loss: 0.3355 - accuracy: 0.9072 - val_loss: 0.3089 - val_accuracy: 0.9144
Epoch 7/10
480/480 [==============================] - 1s 2ms/step - loss: 0.3189 - accuracy: 0.9116 - val_loss: 0.2961 - val_accuracy: 0.9180
Epoch 

In [19]:
#8.Test
model_performance = model.evaluate(X_test,Y_test,batch_size=batch_size)
print('Loss: {}, Accuracy: {}'.format(*model_performance))

100/100 [==============================] - 0s 1ms/step - loss: 0.2679 - accuracy: 0.9255
Loss: 0.2678661346435547, Accuracy: 0.9254999756813049
